import React from 'react';
import { Activity } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export default function PrintReport({ 
  results, 
  preview,
  doctorNotes
}: { 
  results: any, 
  preview: string | null,
  doctorNotes?: string 
}) {
  if (!results) return null;

  return (
    <>
      <style type="text/css">
        {`
          @media print {
            @page { margin: 0; }
            html, body {
              background-color: white !important;
            }
            body { 
              margin: 1.5cm;
              -webkit-print-color-adjust: exact; 
              print-color-adjust: exact; 
            }
          }
        `}
      </style>
      <div className="hidden print:block print:w-full print:bg-white print:text-black font-sans">
        <div className="border-b-2 border-slate-200 pb-6 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 mb-1">Skin Analysis Clinical Report</h1>
            <p className="text-slate-500">Generated by Advanced AI Ensemble</p>
          </div>
          <div className="flex items-center gap-2">
            <Activity className="h-7 w-7 text-primary" />
            <span className="text-2xl font-bold text-slate-900 tracking-tight">Skin Analyzer AI</span>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-8 mb-8">
          <div>
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-4 border-b border-slate-200 pb-2">Patient Image</h2>
            {preview ? (
              <div className="w-48 h-48 rounded-lg overflow-hidden border border-slate-300">
                <img src={preview} alt="Analyzed Skin" className="w-full h-full object-cover" />
              </div>
            ) : (
              <div className="w-48 h-48 rounded-lg border border-slate-300 bg-slate-50 flex items-center justify-center">
                <span className="text-slate-400">No image available</span>
              </div>
            )}
            <p className="text-sm text-slate-500 mt-2">File: {results.filename}</p>
          </div>

          <div>
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-4 border-b border-slate-200 pb-2">Primary Diagnosis</h2>
            <div className="mb-6">
              <h3 className="text-2xl font-bold text-slate-900 mb-1">{results.primary.condition}</h3>
              <p className="text-slate-600 font-medium">Confidence: {results.primary.confidence}%</p>
            </div>

            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-4 border-b border-slate-200 pb-2">Secondary Observations</h2>
            <div>
              <h3 className="text-lg font-bold text-slate-900">{results.secondary.condition}</h3>
              <p className="text-slate-600 font-medium mb-1">Confidence: {results.secondary.confidence}%</p>
              <p className="text-slate-600">Risk/Severity: <span className="font-bold">{results.secondary.severity}</span></p>
            </div>
          </div>
        </div>

        <div className="mb-8">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-4 border-b border-slate-200 pb-2">Automated AI Recommendations</h2>
          <ul className="list-disc pl-5 space-y-3">
            {results.recommendations.map((rec: string, index: number) => (
              <li key={index} className="text-slate-800 text-base leading-relaxed">{rec}</li>
            ))}
          </ul>
        </div>

        {doctorNotes && (
          <div className="mb-8">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-6 border-b border-slate-200 pb-2">Clinical Notes & Prescriptions</h2>
            <div className="pl-4 border-l-4 border-slate-200">
              <ReactMarkdown 
                components={{
                  h3: ({node, ...props}) => <h3 className="text-lg font-bold text-slate-900 mt-8 mb-4 uppercase tracking-wide break-after-avoid" {...props} />,
                  p: ({node, ...props}) => <p className="text-slate-800 text-justify mb-5 leading-relaxed break-inside-avoid" {...props} />,
                  ul: ({node, ...props}) => <ul className="list-disc pl-6 space-y-3 mb-5" {...props} />,
                  li: ({node, ...props}) => <li className="text-slate-800 leading-relaxed text-justify break-inside-avoid" {...props} />,
                  strong: ({node, ...props}) => <strong className="font-bold text-slate-900" {...props} />
                }}
              >
                {doctorNotes}
              </ReactMarkdown>
            </div>
          </div>
        )}

        <div className="mt-16 pt-8 border-t border-slate-200 text-center">
        <p className="text-sm text-slate-500 mb-1">Disclaimer: This report is generated by an AI model and should not replace professional medical advice.</p>
        <p className="text-sm font-bold text-slate-400">Skin Analyzer AI Engine v2.0</p>
      </div>
      </div>
    </>
  );
}
